#pragma once

// #define USE_POSTGRESQL
// #define LIBPQ_SUPPORTS_BATCH_MODE
// #define USE_MYSQL
// #define USE_SQLITE3
#define HAS_STD_FILESYSTEM_PATH
#define OpenSSL

#define COMPILATION_FLAGS "@COMPILATION_FLAGS@@DROGON_CXX_STANDARD@"
#define COMPILER_COMMAND "@COMPILER_COMMAND@"
#define COMPILER_ID "@COMPILER_ID@"

#define INCLUDING_DIRS "@INCLUDING_DIRS@"
